### ISSUE TITLE
Define the pipeline

### ISSUE THREAD

**Issue by rscibelli** [L-E-G/simulator#15]
Sort out which stages our pipeline will include.  I feel like we can just use the basic 5 stage pipeline, but we may need a longer one for out graphics stuff.

**Comment by catvec** [comment]
Good thought about maybe needing an extra stage for our graphics pipeline. I wonder about that to. It seems like the graphics processor (aka blitter) is kind of like one of the computation units we learned about in the multi-threading lectures. We might be able to treat it just like the adder, and assign work to it if it is not busy.

**Comment by catvec** [comment]
Should the stages be:

1. Fetch
2. Decode
3. Execute
4. Memory access
5. Write result

Those were the five basic stages we learned in class.

**Comment by catvec** [comment]
All good.
